site_name: Open MSCS
repo_url: https://github.com/victoriadrake/open-mscs
repo_name: "open-mscs"
nav:
  - Welcome: index.md
  - Course Notes:
      - OMSCS Course Notes: course-notes/index.md
      - Cyber-Physical Systems Security: course-notes/cpss/cyber-physical-systems-security.md
      - Database Systems Concepts and Design: course-notes/db-systems-concepts-design/db-systems-concepts-design.md
      - Introduction to Information Security: course-notes/iis/intro-information-security.md
  - Graduate Life Resources: grad-life-resources.md
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: material/school
    repo: fontawesome/brands/github
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
